---
title: Multiomics reveals persistence of obesity-associated adipose tissue immune
  cell phenotypes during weight loss and weight regain in mice
author: "Matthew A. Cottam"
subtitle: "Supplemental Figure 1"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    theme: journal
    fig_caption: yes
    toc: yes
---

# Setup

```{r prep, warning=FALSE, message=FALSE}
library(RColorBrewer)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(reshape2)
library(viridis)
library(readxl)
library(Seurat)

#Color panels
wccols = c("Lean" = "#878787", "Obese" = "#518db6", "WL" = "#94cc73", "WC" = "#e96b53")
```

# Supplemental Figure 1

```{r Supp2Setup}
#Import Body Mass Data for male mice
bodymass <- read_excel("../Inputs/SuppFig1/SuppFig1_Data.xlsx",sheet=1)
bodymass <- reshape2::melt(bodymass, id.vars=c("MouseID","Time_wk","Group"), measure.vars=colnames(bodymass)[5:32], variable.name="Week", value.name="Bodymass")
colnames(bodymass) <- c("Mouse","Time_wk","Group","Week","Bodymass")
bodymass$Group <- factor(bodymass$Group, levels = c("Lean","Obese","WL","WC"))

#Body Mass Error Calculation for male mice
bodymass_sem <- bodymass %>%
  group_by(Time_wk, Group, Week) %>%
  tidyr::drop_na() %>%
  dplyr::summarize(mean = mean(Bodymass), sd = sd(Bodymass)) 
bodymass_n <- bodymass %>% drop_na() %>% dplyr::count(Time_wk, Group, Week)
bodymass_sem$n <- bodymass_n$n
bodymass_sem <- bodymass_sem %>% mutate(sem = sd/sqrt(n)) %>% tidyr::drop_na()
colnames(bodymass_sem) = c("Time_wk","Group","Week","Bodymass","sd","n","sem")

#Body Composition Data for male mice
bodycomp <- read_excel("../Inputs/SuppFig1/SuppFig1_Data.xlsx", sheet=2)
bodycomp <- reshape2::melt(bodycomp, id.vars=c("MouseID","Time_wk","Group"), measure.vars=colnames(bodycomp)[5:6], variable.name="Source", value.name="Bodycomp")
colnames(bodycomp) <- c("Mouse","Time_wk","Group","Source","Bodycomp")
bodycomp$Group <- factor(bodycomp$Group, levels = c("Lean","Obese","WL","WC"))

#Body Composition Error Calculation for male mice
bodycomp_sem <- bodycomp %>%
  group_by(Time_wk, Group, Source) %>%
  dplyr::summarize(mean = mean(Bodycomp), sd = sd(Bodycomp)) 
bodycomp_n <- bodycomp %>% dplyr::count(Time_wk, Group, Source)
bodycomp_sem$n <- bodycomp_n$n
bodycomp_sem <- bodycomp_sem %>% mutate(sem = sd/sqrt(n)) %>% tidyr::drop_na()
colnames(bodycomp_sem) = c("Time_wk","Group","Source","Bodycomp","sd","n","sem")

#Import ipGTT Data for male mice
gtt <- read_excel("../Inputs/SuppFig1/SuppFig1_Data.xlsx",sheet=3)
gtt <- reshape2::melt(gtt, id.vars=c("MouseID","Time_wk","Group"), measure.vars=colnames(gtt)[5:12], variable.name="Time", value.name="PlasmaGlucose")
gtt$Group <- factor(gtt$Group, levels = c("Lean","Obese","WL","WC"))
gtt <- subset(gtt, PlasmaGlucose!="NA")

#ipGTT Error Calculation for male mice
gtt_sem <- gtt %>%
  group_by(Time_wk, Group, Time) %>%
  tidyr::drop_na() %>%
  dplyr::summarize(mean = mean(PlasmaGlucose), sd = sd(PlasmaGlucose))
gtt_n <- gtt %>% tidyr::drop_na() %>% dplyr::count(Time_wk, Group, Time)
gtt_sem$n <- gtt_n$n
gtt_sem <- gtt_sem %>% mutate(sem = sd/sqrt(n))
colnames(gtt_sem) = c("Time_wk","Group","Time","PlasmaGlucose","sd","n","sem")
```

## Supplemental Figure 1a

This is a biorender schematic of the model time points.

## Supplemental Figure 1b

```{r Supp1a,  fig.width=3, fig.height=3}
#Body Mass over time
ggplot(subset(bodymass, Time_wk==3), aes(x=as.numeric(Week)-1, y=Bodymass, color=Group)) + 
  geom_point(stat="summary", size=2) + 
  geom_line(stat="summary", size=1) +
  geom_errorbar(data=subset(bodymass_sem, Time_wk==3), aes(ymin=Bodymass-sem, ymax=Bodymass+sem), width=0.25) + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="Weeks on Diet", y="Body Mass (g)") +
  scale_x_continuous(breaks=seq(from=0, to=18, by=3)) + 
  ylim(0,60) + 
  scale_color_manual(values=wccols) +
  geom_vline(xintercept = c(9,18), linetype="dashed") 

ggplot(subset(bodymass, Time_wk==9), aes(x=as.numeric(Week)-1, y=Bodymass, color=Group)) + 
  geom_point(stat="summary", size=2) + 
  geom_line(stat="summary", size=1) +
  geom_errorbar(data=subset(bodymass_sem, Time_wk==9), aes(ymin=Bodymass-sem, ymax=Bodymass+sem), width=0.25) + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="Weeks on Diet", y="Body Mass (g)") +
  scale_x_continuous(breaks=seq(from=0, to=18, by=3)) + 
  ylim(0,60) + 
  scale_color_manual(values=wccols) +
  geom_vline(xintercept = c(9,18), linetype="dashed")

ggplot(subset(bodymass, Time_wk==18), aes(x=as.numeric(Week)-1, y=Bodymass, color=Group)) + 
  geom_point(stat="summary", size=2) + 
  geom_line(stat="summary", size=1) +
  geom_errorbar(data=subset(bodymass_sem, Time_wk==18), aes(ymin=Bodymass-sem, ymax=Bodymass+sem), width=0.25) + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="Weeks on Diet", y="Body Mass (g)") +
  scale_x_continuous(breaks=seq(from=0, to=18, by=3)) + 
  ylim(0,60) + 
  scale_color_manual(values=wccols) +
  geom_vline(xintercept = c(9,18), linetype="dashed")

#Body Mass at sacrifice
ggplot(subset(bodymass, Time_wk==3 & Week==3), aes(x=Group, y=Bodymass, fill=Group, color=Group)) + 
  geom_bar(stat="summary",size=0, position="dodge", color="black") + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodymass_sem, Time_wk==3 & Week==3), aes(x=Group, ymin=Bodymass-sem, ymax=Bodymass+sem), width=0.25, color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="", y="Body Mass (g)") +
  ylim(0,60) + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodymass, Time_wk==9 & Week==9), aes(x=Group, y=Bodymass, fill=Group)) + 
  geom_bar(stat="summary",size=0, position="dodge", color="black") + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodymass_sem, Time_wk==9 & Week==9), aes(x=Group, ymin=Bodymass-sem, ymax=Bodymass+sem), width=0.25, color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="", y="Body Mass (g)") +
  ylim(0,60) + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodymass, Time_wk==18 & Week==18), aes(x=Group, y=Bodymass, fill=Group)) + 
  geom_bar(stat="summary",size=0, position="dodge", color="black") +  
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodymass_sem, Time_wk==18 & Week==18), aes(x=Group, ymin=Bodymass-sem, ymax=Bodymass+sem), width=0.25, color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="", y="Body Mass (g)") +
  ylim(0,60) + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

#Sample Size
subset(bodymass, Time_wk==3 | Time_wk==9 | Time_wk==18) %>% 
  subset(., Week==3 | Week==9 | Week==18) %>% 
  group_by(Group,Week,Time_wk) %>% 
  dplyr::count()

#T.tests with Bonferroni correction for multiple comparisons for body mass over time
compare_means(Bodymass ~ Group, data = subset(bodymass, Time_wk==3) %>% tidyr::drop_na(), group.by="Week", method="t.test", p.adjust.method="bonferroni")
compare_means(Bodymass ~ Group, data = subset(bodymass, Time_wk==9) %>% tidyr::drop_na(), group.by="Week", method="t.test", p.adjust.method="bonferroni")
compare_means(Bodymass ~ Group, data = subset(bodymass, Time_wk==18) %>% tidyr::drop_na(), group.by="Week", method="t.test", p.adjust.method="bonferroni")

#T.tests with Bonferroni correction for multiple comparisons for body mass at sacrifice
compare_means(Bodymass ~ Group, data = subset(bodymass, Time_wk==3) %>% tidyr::drop_na(), group.by="Week", method="t.test", p.adjust.method="bonferroni")
compare_means(Bodymass ~ Group, data = subset(bodymass, Time_wk==9) %>% tidyr::drop_na(), group.by="Week", method="t.test", p.adjust.method="bonferroni")
compare_means(Bodymass ~ Group, data = subset(bodymass, Time_wk==18) %>% tidyr::drop_na(), group.by="Week", method="t.test", p.adjust.method="bonferroni")
```

## Supplemental Figure 1C and D

```{r Supp1candd, fig.height=3, fig.width=3}
ggplot(subset(bodycomp,Source=="Lean_mass" & Time_wk==3), aes(x=Group, y=Bodycomp, fill=Group)) + 
  geom_bar(stat="summary", color="black", size=0) + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodycomp_sem, Source=="Lean_mass" & Time_wk==3), aes(ymin=Bodycomp-sem, ymax=Bodycomp+sem), width=0.25, color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() +  
  ylim(0,30) +
  labs(x="", y="Lean Mass (g)") + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodycomp,Source=="Lean_mass" & Time_wk==9), aes(x=Group, y=Bodycomp, fill=Group)) + 
  geom_bar(stat="summary", color="black", size=0) + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodycomp_sem, Source=="Lean_mass" & Time_wk==9), aes(ymin=Bodycomp-sem, ymax=Bodycomp+sem), width=0.25, color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() +  
  ylim(0,30) +
  labs(x="", y="Lean Mass (g)") + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodycomp,Source=="Lean_mass" & Time_wk==18), aes(x=Group, y=Bodycomp, fill=Group)) + 
  geom_bar(stat="summary",color="black", size=0) + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodycomp_sem, Source=="Lean_mass" & Time_wk==18), aes(ymin=Bodycomp-sem, ymax=Bodycomp+sem), width=0.25,color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() +  
  ylim(0,30) +
  labs(x="", y="Lean Mass (g)") + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodycomp,Source=="Fat_mass" & Time_wk==3), aes(x=Group, y=Bodycomp, fill=Group)) + 
  geom_bar(stat="summary",color="black", size=0) + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodycomp_sem, Source=="Fat_mass" & Time_wk==3), aes(ymin=Bodycomp-sem, ymax=Bodycomp+sem), width=0.25,color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() +  
  ylim(0,25) +
  labs(x="", y="Fat Mass (g)") + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodycomp,Source=="Fat_mass" & Time_wk==9), aes(x=Group, y=Bodycomp, fill=Group)) + 
  geom_bar(stat="summary",color="black", size=0) + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodycomp_sem, Source=="Fat_mass" & Time_wk==9), aes(ymin=Bodycomp-sem, ymax=Bodycomp+sem), width=0.25,color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() +   
  ylim(0,25) +
  labs(x="", y="Fat Mass (g)") + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

ggplot(subset(bodycomp,Source=="Fat_mass" & Time_wk==18), aes(x=Group, y=Bodycomp, fill=Group)) + 
  geom_bar(stat="summary", color="black", size=0) + 
  geom_jitter(color="black", alpha=0.5, width=0.3) +
  geom_errorbar(data=subset(bodycomp_sem, Source=="Fat_mass" & Time_wk==18), aes(ymin=Bodycomp-sem, ymax=Bodycomp+sem), width=0.25, color="black") + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  ylim(0,25) +
  labs(x="", y="Fat Mass (g)") + 
  scale_fill_manual(values=wccols) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

### T.test with Bonferroni correction for multiple comparisons
# Lean Mass
compare_means(Bodycomp ~ Group, data = subset(bodycomp,Source=="Lean_mass" & Time_wk==3), method="t.test", p.adjust.method = "bonferroni") 
compare_means(Bodycomp ~ Group, data = subset(bodycomp,Source=="Lean_mass" & Time_wk==9), method="t.test", p.adjust.method = "bonferroni") 
compare_means(Bodycomp ~ Group, data = subset(bodycomp,Source=="Lean_mass" & Time_wk==18), method="t.test", p.adjust.method = "bonferroni") 

# Fat Mass
compare_means(Bodycomp ~ Group, data = subset(bodycomp,Source=="Fat_mass" & Time_wk==3), method="t.test", p.adjust.method = "bonferroni") 
compare_means(Bodycomp ~ Group, data = subset(bodycomp,Source=="Fat_mass" & Time_wk==9), method="t.test", p.adjust.method = "bonferroni")  
compare_means(Bodycomp ~ Group, data = subset(bodycomp,Source=="Fat_mass" & Time_wk==18), method="t.test", p.adjust.method = "bonferroni") 
```

## Supplemental Figure 1e

```{r Supp1c, fig.height=3, fig.width=3}
ggplot(subset(gtt, Time_wk==3), aes(x=as.numeric(as.character(Time)), y=PlasmaGlucose, color=Group)) + 
  geom_point(stat="summary", size=2) + 
  geom_line(stat="summary", size=1) +
  geom_errorbar(data=subset(gtt_sem, Time_wk==3), aes(ymin=PlasmaGlucose-sem, ymax=PlasmaGlucose+sem), width=0.25) + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="Time (min)", y="Plasma Glucose (mg/dL)") +
  scale_x_continuous(breaks=seq(from=0, to=150, by=30)) + 
  ylim(0,600) + 
  scale_color_manual(values=wccols) 

ggplot(subset(gtt, Time_wk==9), aes(x=as.numeric(as.character(Time)), y=PlasmaGlucose, color=Group)) + 
  geom_point(stat="summary", size=2) + 
  geom_line(stat="summary", size=1) +
  geom_errorbar(data=subset(gtt_sem, Time_wk==9), aes(ymin=PlasmaGlucose-sem, ymax=PlasmaGlucose+sem), width=0.25) + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="Time (min)", y="Plasma Glucose (mg/dL)") +
  scale_x_continuous(breaks=seq(from=0, to=150, by=30)) + 
  ylim(0,600) + 
  scale_color_manual(values=wccols) 

ggplot(subset(gtt, Time_wk==18), aes(x=as.numeric(as.character(Time)), y=PlasmaGlucose, color=Group)) + 
  geom_point(stat="summary", size=2) + 
  geom_line(stat="summary", size=1) +
  geom_errorbar(data=subset(gtt_sem, Time_wk==18), aes(ymin=PlasmaGlucose-sem, ymax=PlasmaGlucose+sem), width=0.25) + 
  theme_pubr(base_size=12) +
  NoLegend() + 
  labs(x="Time (min)", y="Plasma Glucose (mg/dL)") +
  scale_x_continuous(breaks=seq(from=0, to=150, by=30)) + 
  ylim(0,600) + 
  scale_color_manual(values=wccols) 

#ANOVA
compare_means(PlasmaGlucose ~ Group, data = subset(gtt, Time_wk==3), group.by="Time",method="anova") #By time
compare_means(PlasmaGlucose ~ Group, data = subset(gtt, Time_wk==9), group.by="Time",method="anova") 
compare_means(PlasmaGlucose ~ Group, data = subset(gtt, Time_wk==18), group.by="Time",method="anova") 

#T.tests with Bonferroni correction for multiple comparisons
compare_means(PlasmaGlucose ~ Group, data = subset(gtt, Time_wk==3), group.by="Time", method="t.test", p.adjust.method="bonferroni")
compare_means(PlasmaGlucose ~ Group, data = subset(gtt, Time_wk==9), group.by="Time", method="t.test", p.adjust.method="bonferroni")
compare_means(PlasmaGlucose ~ Group, data = subset(gtt, Time_wk==18), group.by="Time", method="t.test", p.adjust.method="bonferroni")

```

# Session Info

```{r si}
sessionInfo()
```

